# Generated by Django 5.0.6 on 2024-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatgpt", "0002_rename_talk_item_talkitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talkitem",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
